### ISSUE TITLE
Sapper support

### ISSUE THREAD

**Issue by AndreasHald** [unlocomqx/svelte-reactive-preprocessor#1]
Does this support sapper? and SSR in general? i've tried installing to use your reactive debugger but get the following error:

```
window.rpDsp = window.rpDsp || function () {
^

ReferenceError: window is not defined
```

**Comment by unlocomqx** [comment]
Hi,
Thanks for reporting, do you have an example to reproduce the issue, I'm not familiar with svelte ssr

I made a change though to avoid the error, it's in version 0.5.1
npm i svelte-reactive-preprocessor@0.5.1

**Comment by AndreasHald** [comment]
Hi again, sorry it took some time i was in the middle of something. But thanks for responding so quickly!

So SSR in svelte can be handled in multiple ways, but the most common (i think) is sapper. 

Basically a Node.js server which renders the html in a virtual browser (which is why window, and other browser variables are not there) before passing it to the client. and Svelte then hydrates and takes over.

Your fix in 0.5.1 removed the window error, but it's still unable to build correctly, the error is now ```ReferenceError: Can't find variable: global```

I've created a small repo that reproduces the issue with sapper starter https://github.com/AndreasHald/svelte-reactive-preprocessor-debug

**Comment by unlocomqx** [comment]
Thank you for the repro, I managed to avoid the error
svelte-reactive-preprocessor@0.5.2

Note that you can disable the preprocessor on the production build by setting the enabled option to false
https://github.com/unlocomqx/svelte-reactive-preprocessor#options-optional

Cheers

**Comment by AndreasHald** [comment]
That fixed it for my repo. Unfortunately in our project it still has an error
```$$self is not defined```

Originating from here
![Screenshot 2021-01-18 at 21 44 04](https://user-images.githubusercontent.com/8914722/104961299-52aee880-59d6-11eb-9a4d-4d9c22896800.png)
Unfortunately my understanding of what happens here is limited, so i don't know how i would reproduce it.

Do you have any ideas?

**Comment by unlocomqx** [comment]
The $$self error occurs when svelte dev mode is not enabled, it's better to disable the preprocessor on ssr or production mode. Please check if you can do that, you can use the dev variable and pass it to the preprocessor like this
```
reactivePreprocess({
  enabled: dev
})
```

**Comment by unlocomqx** [comment]
I found a simple way to avoid the error even when dev mode is not enabled. I pushed version svelte-reactive-preprocessor@0.5.3

**Comment by AndreasHald** [comment]
Just tried out svelte-reactive-preprocessor@6.0.0 and unfortunately i still get the issue even after setting dev mode 
```
reactivePreprocess({
  enabled: isDev
})
```

This appears to be an issue with out setup, so until i can create a reproduceable example i will close the issue. because it works for sapper starter template now :)
